### PR TITLE
Rebase vulcand dependencies to new location

### PR DESCRIPTION
**Pull request by archisgore**
Due to the change of vulcand from github.com/mailgun/vulcand to github.com/vulcand/vulcand, and based on how go needs explicit paths to each package, this change is necessary.

This change does the following:
1. Replace all references to github.com/mailgun/vulcand to github.com/vulcand/vulcand.
2. Updated godep paths/manifest.
3. Build and run tests.
4. Go fmt.

Since this is a rather large change, I'll hold this for a couple of days and allow at least one other reviewer to take a look.

### CODE REVIEW

**Comment by archisgore** [comment]
I'm going to pull/run this change on one of our production hosts.. that'll be a secondary test to ensure some weird dependency/path didn't break the runtime.

**Comment by tboerger** [comment]
I can switch the webhippie/vulcand docker container... got a LOT downloads.

**Comment by archisgore** [comment]
Awesome. We add custom middlewares, so we use the vbundle method. tboerger@ if you take a cursory look and sign off I'd like to merge this in ASAP.

My rationale is - until the paths are right, this repo is as good as "broken". Even if I cause a break fast and find it, I can fix it, and get it to a usable state.

As we speak, I've vbundled this new one and am running some smoke tests.

**Comment by archisgore** [comment]
@tboerger It's all yours. :-) Go ahead and repoint the docker build anytime you wish. I'm looking into plugging in Travis back again so PRs get verified.

**Pull request merged**
