### PR TITLE
/tmp fillup bugfix

### PR DESCRIPTION
**Pull request by martingartonft**
grab fix from :
https://github.com/mjgarton/multibuf/commit/b9a1261a65e5c6c6f835bcee2e16df4b47323b32

### CODE REVIEW

**Comment by tboerger** [comment]
This should be fixed upstream first and than we need to update the Godeps reference.

**Comment by martingartonft** [comment]
I did submit this upstream first, but there has been no response.

**Comment by tboerger** [comment]
@klizhentas what's up with the upstream project?

**Comment by klizhentas** [comment]
turns out I forgot to set `watching` in github, sorry just merged it

**Comment by archisgore** [comment]
I'm going to push this change as a re-vendor of the mailgun/multibuf package
https://github.com/vulcand/vulcand/commit/f0953ab9e0b8d6bc7189ac3bdb8485ebe5d19793

**Pull request closed without merging**
