### PR TITLE
Update Dependencies and fix vbundle

### PR DESCRIPTION
**Pull request by pquerna**
- In 9b77a77047d6ea1695044b53c4acd82b5a4528db fix vbundle import path to Logrus
- In a44457f46aa77748249cb32844423239c8f0d57c update `scroll.NewApp()` which now can return an `error`
- In 85e9aa2acab158d43011d0bc6e438a5450a6a7d3 update makefile target
- In b0eaeb247029157e5ef75ba034f669b1dd09a741 run makefile target

### CODE REVIEW

**Comment by agalitsyn** [comment]
`.travis.yml` should be fixed too, it's go 1.5 here, and you have 1.6 in `packages.json`

**Comment by klizhentas** [comment]
the tests are really flaky - so it's hard to tell if they are failing because of re-vendoring or just by themselves. Have you tried running tests locally?

**Comment by gchaincl** [comment]
Can https://github.com/vulcand/vulcand/commit/42d5d7ceeefe6c2838a226e0928874ed4712553d be merged?

**Comment by pquerna** [comment]
Redone using current dependencies and for other upstream changes.

**Pull request merged**
